// <auto-generated />
using ApiPessoa2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPessoa2.Migrations
{
    [DbContext(typeof(PessoaContext))]
    [Migration("20210910203820_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ApiPessoa2.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "00000000001",
                            Email = "gabriel@gmail.com",
                            Nome = "Gabriel",
                            Sobrenome = "de Almeida"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "00000000002",
                            Email = "rosana@gmail.com",
                            Nome = "Rosana",
                            Sobrenome = "Maia"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "00000000003",
                            Email = "rayanna@gmail.com",
                            Nome = "Rayanna",
                            Sobrenome = "Almeida"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
